### ISSUE TITLE
How does the node connect to the vision position estimate plugin?

### ISSUE THREAD

**Issue by erikasnow** [hoangthien94/vision_to_mavros#7]
Hey @hoangthien94, could you explain where you're sending the vision pose so that the VISION_POSE_ESTIMATE message is sent to mavlink? I'm new to the c++ side of ros and I can't seem to figure it out by looking at the source code

**Comment by hoangthien94** [comment]
Additionally, the `VISION_POSE_ESTIMATE` message is received by `mavros` through the topic `/mavros/vision_pose/pose`. All the nodes are launched at once here: https://github.com/hoangthien94/vision_to_mavros/blob/master/launch/t265_all_nodes.launch

**Comment by erikasnow** [comment]
Awesome thank you so much! That's exactly what I needed
